### ISSUE TITLE
Add 4:3 Support

### ISSUE THREAD

**Issue by BillZhou233** [CatalinTermure/Cytoid-Chart-Editor#18]
A large number of the Cytoid players use iPads with 4:3 screen. It may be essential to add a support for this in order to preview the chart in this screen ratio. Meanwhile, this also makes charting on iPad more comfortable maybe.

**Comment by CatalinTermure** [comment]
I am not sure what you would want to be fixed. Currently the UI looks fine on 4:3 ratio screens in my opinion. If you are trying to say that some tweaks should be done to adjust for 4:3 screens, then I will gladly listen to feedback on what looks wrong.

**Comment by BillZhou233** [comment]
I’m not going to report a bug but I think this may be an enhancement of composing area.

The UI looks fine on my iPad, but the composing area is more likely to a widescreen one, to which I’m not accustomed.

Personally, I think Cytoid charters may need to check how the charts look on different screen ratios. Maybe the width and height of the composing area should be flexible so that it can simulate different screens. Also, you could refer to the solution in PCtyx, in which there is a toggle between 16:9 and 4:3 composing area.

Also, plz forgive my poor English...

**Comment by CatalinTermure** [comment]
Understood, I will add an option for different play area ratios/sizes. I agree on your point that the play area looks like it was made for a widescreen. If anything else looks off on a 4:3 screen, add to this issue.

Also, no worries about your English, I understood you just fine.

**Comment by CatalinTermure** [comment]
![image](https://user-images.githubusercontent.com/32488274/96338314-c7038400-1095-11eb-9cbe-b75f159d9a27.png)
This looks good, right?

**Comment by BillZhou233** [comment]
OK, thanks!
