### ISSUE TITLE
About Overwriting Notes

### ISSUE THREAD

**Issue by BillZhou233** [CatalinTermure/Cytoid-Chart-Editor#2]
When clicking a existing note on the chart with the note tool, the editor will simply put a new note on the existing one, which may cause confusion. The expected behavior is that the editor will overwrite the existing one with the new one, with the note type updated, like PCtyx Editor.

**Comment by CatalinTermure** [comment]
Noted, will be fixed next update.

**Comment by CatalinTermure** [comment]
Fixed in the latest update.
