### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Nintendomakell** [CatalinTermure/Cytoid-Chart-Editor#3]
This made be a Stupid or not good idea but a record Button From:NoahBottle

**Comment by CatalinTermure** [comment]
The engine the editor runs on doesn't support something like this, so this would take way too much development time and when compared to the payoffs, it simply is not worth it. You can record the screen with 3rd party programs on Android(audio too, starting with Android 10) and iOS already has this feature on most devices, so it doesn't seem worth from the perspective of it becoming obsolete soon either.
With these in mind, I'll just close this issue as it's not worth implementing, thank you for the idea though and I hope you understand this.

**Comment by Nintendomakell** [comment]
Ok
