### ISSUE TITLE
Unable to load charts

### ISSUE THREAD

**Issue by jojang-orange** [CatalinTermure/Cytoid-Chart-Editor#36]
id: io.cytoid.sky
     he-wurenqu
and many more

**Comment by camelCase-dumb** [comment]
You need to configure manually your level.json first.
Put it in a folder together with background and music and preview music.

This part is very important.
  "charts": [
    {
      "type": "easy",
      "difficulty": 6,
      "path": "easy.chart"
    }
  ]

You must create easy.chart file inside the folder.
After that open the editor and press chart select.

And at the left side there is a file explorer, you must navigate that to your chart folder.

And press search for levels.

The editor will let you know that there is an error.

**Comment by jojang-orange** [comment]
But that's not the point,I was talking about the format of the chart
Error while load charts
chart id : io.cytoid.sky


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CatalinTermure/Cytoid-Chart-Editor"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午3:56
收件人:&nbsp;"CatalinTermure/Cytoid-Chart-Editor"<Cytoid-Chart-Editor@noreply.github.com&gt;;
抄送:&nbsp;"jojang"<1214928006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CatalinTermure/Cytoid-Chart-Editor] Unable to load charts (#36)





 
You need to configure manually your level.json first.
 Put it in a folder together with background and music and preview music.
 
This part is very important.
 "charts": [
 {
 "type": "easy",
 "difficulty": 6,
 "path": "easy.chart"
 }
 ]
 
You must create easy.chart file inside the folder.
 After that open the editor and press chart select.
 
And at the left side there is a file explorer, you must navigate that to your chart folder.
 
And press search for levels.
 
The editor will let you know that there is an error.

**Comment by CatalinTermure** [comment]
The chart is in C1 file format.
This chart editor can only load C2 file format charts and I am not planning to add C1 format support. I'm sorry for the inconvenience, you may use a C1 to C2 converter if you want to open it.
