### ISSUE TITLE
Add option to delete chart

### ISSUE THREAD

**Issue by CatalinTermure** [CatalinTermure/Cytoid-Chart-Editor#48]

**Comment by ArthDJ** [comment]
Hello! I want to make a level... How do I acces to the level editor ?

**Comment by CatalinTermure** [comment]
Check the wiki, it has all the needed information https://github.com/CatalinTermure/Cytoid-Chart-Editor/wiki/Getting-started .

**Comment by ArthDJ** [comment]
> Check the wiki, it has all the needed information https://github.com/CatalinTermure/Cytoid-Chart-Editor/wiki/Getting-started .

Thanks but how do I get to the main screen (I can't open the app...)?

**Comment by CatalinTermure** [comment]
What device and OS version are you using?

**Comment by ArthDJ** [comment]
> What device and OS version are you using?

An Iphone with 14.4.1 IOS version...

**Comment by CatalinTermure** [comment]
Sorry, but there are no valid iOS builds available. The TestFlight build that you were using until now has expired.

There **may**(not guaranteed) be an iOS build when the next version releases, which would be at the start of next month most likely(taking into account the time it takes for Apple's verification).

**Comment by ArthDJ** [comment]
> Sorry, but there are no valid iOS builds available. The TestFlight build that you were using until now has expired.
> 
> There may(not guaranteed) be an iOS build when the next version releases, which would be at the start of next month most likely(taking into account the time it takes for Apple's verification).
Ok, maybe next time... thank you !

**Comment by ArthDJ** [comment]
> Sorry, but there are no valid iOS builds available. The TestFlight build that you were using until now has expired.
> 
> There **may**(not guaranteed) be an iOS build when the next version releases, which would be at the start of next month most likely(taking into account the time it takes for Apple's verification).

Ok, maybe next time... Thank you
